#!/usr/bin/env node

var fs = require('fs');
var through = require('through');
var split = require('split');
var _ = require('lodash');

var fsa = require('./fsa');

var falafel = require('falafel');
var opt = require('optimist')
    .usage([
      'Analyse Twitter Flight code. Listens to stdin, pipes JSON to stdout.',
      '',
      '  echo "./path/to/file.js" | flight-static-analysis',
      '',
      'Reccommended usage:',
      '  tree-watch ./path/to/flight/code "**/*.js" | flight-static-analysis | json-stream-(socket|server)'
    ].join('\n'))
    .alias('i', 'instances')
    .describe('i', 'Include instance data, if plugin supports it.')
    .alias('h', 'help')
    .describe('h', 'Show this help message')
var argv = opt.argv;

if (argv.h) {
  return opt.showHelp();
}

/**
 * Read a file with utf-8 encoding.
 * TODO make this a bound-right fn: fs.readFileSync.bindRight(fs, { ... })?
 */
var read = function (f) {
  return fs.readFileSync(f, {
    encoding: 'utf-8'
  });
};

/**
 * Default plugins.
 * TODO make this come from args
 */
var plugins = [
  // 'inspect',
  'name',
  'event',
  'mixin',
  'advice',
  'dependency',
  'method',
  'defaultAttrs',
  'selector',
  'domClimbing',
  'jQuery',
];

var output = function (name, data) {
  return JSON.stringify({
    name: name,
    data: data
  }) + '\n';
};

var processLine = function (filename) {
  if (!filename.length) return;

  // Read & process the file, then queue the result
  try {
    this.queue(
      output(filename, fsa(read(filename), {
        plugins: plugins,
        argv: argv
      }))
    );
  } catch (e) {
    this.queue(output(filename, {
      error: {
        message: 'Failed to process ' + filename,
        stack: e.stack
      }
    }));
  }
};

process.stdin
  .pipe(split())
  .pipe(through(processLine))
  .pipe(process.stdout);
